grafana:
  enabled: false

prometheus:
  service:
    type: NodePort
    nodePort: 9090
  prometheusSpec:
    retention: 7d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

