version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python backend/api.py
    ports:
      - "5001:5001"
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=5001
      - VAULT_ADDR=http://host.docker.internal:8200
      - VAULT_TOKEN=root
      - VAULT_SECRET_PATH=cubbyhole/asmaa
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python frontend/app.py
    ports:
      - "5000:5000"
    environment:
      - FRONTEND_HOST=0.0.0.0
      - FRONTEND_PORT=5000
      - BACKEND_URL=http://backend:5001
      - PROMETHEUS_URL=http://localhost:${PROMETHEUS_HOST_PORT:-9091}
      - GRAFANA_URL=http://localhost:${GRAFANA_HOST_PORT:-3001}
      - VAULT_UI_URL=http://localhost:8200
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "${PROMETHEUS_HOST_PORT:-9091}:9090"
    user: root
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/asmaa/app/prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_HOST_PORT:-3001}:3000"
    user: root
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - /home/asmaa/app/grafana-data:/var/lib/grafana
      - ./monitoring/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./monitoring/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
