{
 "title": "Request Outcomes",
 "tags": [
  "backend",
  "frontend-actions",
  "prometheus",
  "devops-platform"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(app_http_requests_total[$__range]))"
    }
   ]
  },
  {
   "title": "200 OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(app_http_requests_total{status=\"200\"}[$__range]))"
    }
   ]
  },
  {
   "title": "404 Not Found",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(app_http_requests_total{status=\"404\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Failed 5xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(app_http_requests_total{status=~\"5..\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Request Rate By Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(app_http_requests_total[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests By Status In Selected Time Range",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (increase(app_http_requests_total[$__range]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests By Endpoint And Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (exported_endpoint, status) (increase(app_http_requests_total[$__range]))"
    }
   ]
  }
 ]
}